version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:sgm@db:3306/sgm
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: sgm
      MYSQL_DATABASE: sgm
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: